# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zyk/.tmp/LuoguDesktop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zyk/.tmp/LuoguDesktop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyk/.tmp/LuoguDesktop/CMakeFiles /home/zyk/.tmp/LuoguDesktop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyk/.tmp/LuoguDesktop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LuoguDesktop

# Build rule for target.
LuoguDesktop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuoguDesktop
.PHONY : LuoguDesktop

# fast build rule for target.
LuoguDesktop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/build
.PHONY : LuoguDesktop/fast

#=============================================================================
# Target rules for targets named LuoguDesktop_autogen_timestamp_deps

# Build rule for target.
LuoguDesktop_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuoguDesktop_autogen_timestamp_deps
.PHONY : LuoguDesktop_autogen_timestamp_deps

# fast build rule for target.
LuoguDesktop_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop_autogen_timestamp_deps.dir/build.make CMakeFiles/LuoguDesktop_autogen_timestamp_deps.dir/build
.PHONY : LuoguDesktop_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named LuoguDesktop_autogen

# Build rule for target.
LuoguDesktop_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuoguDesktop_autogen
.PHONY : LuoguDesktop_autogen

# fast build rule for target.
LuoguDesktop_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop_autogen.dir/build.make CMakeFiles/LuoguDesktop_autogen.dir/build
.PHONY : LuoguDesktop_autogen/fast

LuoguDesktop_autogen/mocs_compilation.o: LuoguDesktop_autogen/mocs_compilation.cpp.o
.PHONY : LuoguDesktop_autogen/mocs_compilation.o

# target to build an object file
LuoguDesktop_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/LuoguDesktop_autogen/mocs_compilation.cpp.o
.PHONY : LuoguDesktop_autogen/mocs_compilation.cpp.o

LuoguDesktop_autogen/mocs_compilation.i: LuoguDesktop_autogen/mocs_compilation.cpp.i
.PHONY : LuoguDesktop_autogen/mocs_compilation.i

# target to preprocess a source file
LuoguDesktop_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/LuoguDesktop_autogen/mocs_compilation.cpp.i
.PHONY : LuoguDesktop_autogen/mocs_compilation.cpp.i

LuoguDesktop_autogen/mocs_compilation.s: LuoguDesktop_autogen/mocs_compilation.cpp.s
.PHONY : LuoguDesktop_autogen/mocs_compilation.s

# target to generate assembly for a file
LuoguDesktop_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/LuoguDesktop_autogen/mocs_compilation.cpp.s
.PHONY : LuoguDesktop_autogen/mocs_compilation.cpp.s

src/Login.o: src/Login.cpp.o
.PHONY : src/Login.o

# target to build an object file
src/Login.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/Login.cpp.o
.PHONY : src/Login.cpp.o

src/Login.i: src/Login.cpp.i
.PHONY : src/Login.i

# target to preprocess a source file
src/Login.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/Login.cpp.i
.PHONY : src/Login.cpp.i

src/Login.s: src/Login.cpp.s
.PHONY : src/Login.s

# target to generate assembly for a file
src/Login.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/Login.cpp.s
.PHONY : src/Login.cpp.s

src/LuoguDesktop.o: src/LuoguDesktop.cpp.o
.PHONY : src/LuoguDesktop.o

# target to build an object file
src/LuoguDesktop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/LuoguDesktop.cpp.o
.PHONY : src/LuoguDesktop.cpp.o

src/LuoguDesktop.i: src/LuoguDesktop.cpp.i
.PHONY : src/LuoguDesktop.i

# target to preprocess a source file
src/LuoguDesktop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/LuoguDesktop.cpp.i
.PHONY : src/LuoguDesktop.cpp.i

src/LuoguDesktop.s: src/LuoguDesktop.cpp.s
.PHONY : src/LuoguDesktop.s

# target to generate assembly for a file
src/LuoguDesktop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/LuoguDesktop.cpp.s
.PHONY : src/LuoguDesktop.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuoguDesktop.dir/build.make CMakeFiles/LuoguDesktop.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LuoguDesktop_autogen"
	@echo "... LuoguDesktop_autogen_timestamp_deps"
	@echo "... LuoguDesktop"
	@echo "... LuoguDesktop_autogen/mocs_compilation.o"
	@echo "... LuoguDesktop_autogen/mocs_compilation.i"
	@echo "... LuoguDesktop_autogen/mocs_compilation.s"
	@echo "... src/Login.o"
	@echo "... src/Login.i"
	@echo "... src/Login.s"
	@echo "... src/LuoguDesktop.o"
	@echo "... src/LuoguDesktop.i"
	@echo "... src/LuoguDesktop.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

